# Generated by Django 2.1.2 on 2018-10-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('plate', models.CharField(max_length=8, null=True)),
                ('acc', models.FloatField(max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='static/users/profile_pics'),
        ),
    ]
