# Generated by Django 2.1.2 on 2018-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181018_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargemap.City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='users/profile_pics'),
        ),
    ]
