# Generated by Django 2.1.2 on 2018-10-22 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20181019_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_charges', models.IntegerField(null=True)),
                ('cunsumed_power', models.FloatField(max_length=5, null=True)),
                ('balance', models.FloatField(max_length=5, null=True)),
                ('bonus_balance', models.FloatField(max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_driving_license',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
