# Generated by Django 2.1.1 on 2018-10-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_station_name', models.CharField(max_length=100)),
                ('charge_station_operator', models.CharField(max_length=100)),
                ('charge_station_maxpower', models.IntegerField()),
                ('charge_station_score', models.FloatField()),
                ('charge_station_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeStationPlugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plug_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeStationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeStationWorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_plug',
            field=models.ManyToManyField(to='chargemap.ChargeStationPlugType'),
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_status',
            field=models.ManyToManyField(to='chargemap.ChargeStationStatus'),
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_working_time',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationWorkingTime'),
        ),
    ]
