# Generated by Django 2.1.1 on 2018-10-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeStationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_latitude',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='chargestation',
            name='harge_station_longtitude',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.RemoveField(
            model_name='chargestation',
            name='charge_station_status',
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationStatus'),
        ),
        migrations.AddField(
            model_name='chargestation',
            name='charge_station_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationType'),
        ),
    ]
