# Generated by Django 2.1.2 on 2018-10-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationoperator',
            name='site',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
