# Generated by Django 2.1.2 on 2018-10-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0002_auto_20181016_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_description',
            field=models.TextField(default='Станция зарядки электромобилей', max_length=300),
        ),
    ]
