# Generated by Django 2.1.2 on 2018-10-16 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0003_auto_20181016_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_name',
            field=models.CharField(default='Зарядная станция', max_length=100),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_status',
            field=models.ForeignKey(default='Нет данных', on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationStatus'),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_type',
            field=models.ForeignKey(default='Нет данных', on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationType'),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_working_time',
            field=models.ForeignKey(default='Нет данных', on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationWorkingTime'),
        ),
    ]
