# Generated by Django 2.1.2 on 2018-10-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0004_auto_20181016_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationType'),
        ),
    ]
