# Generated by Django 2.1.2 on 2018-10-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0005_auto_20181016_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_city',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='chargemap.City'),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationStatus'),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationType'),
        ),
        migrations.AlterField(
            model_name='chargestation',
            name='charge_station_working_time',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chargemap.ChargeStationWorkingTime'),
        ),
    ]
