# Generated by Django 2.1.2 on 2018-11-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargemap', '0006_auto_20181018_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_longtitude',
            new_name='longtitude',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_maxpower',
            new_name='maxpower',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_operator',
            new_name='operator',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_plug',
            new_name='plug',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_type',
            new_name='station_type',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='chargestation',
            old_name='charge_station_working_time',
            new_name='working_time',
        ),
        migrations.RenameField(
            model_name='chargestationworkingtime',
            old_name='working_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='chargestation',
            name='station_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
